
void init_sh(){
  pinrtf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdddmNMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyhmMMMNho+osso/ohMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMNs/+////+oy++yNMMMMms/sMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMNy//+osso//+//dMMMMMMMMo/dMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMNy+/::/oyyy+++/++dMMMMMMN+/mMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMNy//://///+syyyy+:++MMMMMho+yMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMNs//:///:::://+osss/++MMMdo+smMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMNs/::///::::::::://///sNMho+smMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMNs/::://::::::::::::::omMdo+smMMNMMMMMNMMMMMMMMM\nMMMMMMMMMMNs/::://::::::::::::::smMho+smMMMMNmNMNmNMMMMMMMMM\nMMMMMMMMNs/:::///:::::::::::::smMMs+smMNNNNNN****mNNNNNMMMMM\nMMMMMMNs/::://:::::::::--:::smMMMh+oMMMMM****ysssy**NMMMMMMM\nMMMMMMy::://::::::::::::::smMMMMMd++MMMMMM**yyss**hmNMMMMMMM\nMMMMMMy://:::::::::::///smMMMMMMMMs/odNNNm**oyy**mNmNNNMMMMM\nMMMMMMN+::::::::::-::/smMMMMMMMMMMMdyo+++++sddNNmmNMMMMMMMMM\nMMMMMMMNy/::::::::::smMMMMMMMMMMMMMMMMNNNNMMNMMMMNNMMMMMMMMM\nMMMMMMMMMNy+::::::smMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMNmdddNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n\n");
  printf("Welcome To TnT Shell!! \n");
    }

void redirection(){

}

void eval(){

}

void main(){
  init_shell();
}
